// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CounterModuleScssNamespace {
  export interface ICounterModuleScss {
    parentCounter: string;
  }
}

declare const CounterModuleScssModule: CounterModuleScssNamespace.ICounterModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CounterModuleScssNamespace.ICounterModuleScss;
};

export = CounterModuleScssModule;
