// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace GridModuleScssNamespace {
  export interface IGridModuleScss {
    containerWrapper: string;
  }
}

declare const GridModuleScssModule: GridModuleScssNamespace.IGridModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GridModuleScssNamespace.IGridModuleScss;
};

export = GridModuleScssModule;
