// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CellModuleScssNamespace {
  export interface ICellModuleScss {
    bombEntity: string;
    bombFrame: string;
    changedBorderColor: string;
    closedFrame: string;
    emptyFrame: string;
    transparentClosedFrame: string;
  }
}

declare const CellModuleScssModule: CellModuleScssNamespace.ICellModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CellModuleScssNamespace.ICellModuleScss;
};

export = CellModuleScssModule;
