// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LevelModuleScssNamespace {
  export interface ILevelModuleScss {
    optionLevel: string;
    selectLevel: string;
  }
}

declare const LevelModuleScssModule: LevelModuleScssNamespace.ILevelModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LevelModuleScssNamespace.ILevelModuleScss;
};

export = LevelModuleScssModule;
