// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LegendModuleScssNamespace {
  export interface ILegendModuleScss {
    firstAction: string;
    flagComboParent: string;
    legendParent: string;
    secondAction: string;
  }
}

declare const LegendModuleScssModule: LegendModuleScssNamespace.ILegendModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LegendModuleScssNamespace.ILegendModuleScss;
};

export = LegendModuleScssModule;
