// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ResetModuleScssNamespace {
  export interface IResetModuleScss {
    resetButton: string;
  }
}

declare const ResetModuleScssModule: ResetModuleScssNamespace.IResetModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ResetModuleScssNamespace.IResetModuleScss;
};

export = ResetModuleScssModule;
