// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ScoreboardModuleScssNamespace {
  export interface IScoreboardModuleScss {
    wrapperScoreboard: string;
  }
}

declare const ScoreboardModuleScssModule: ScoreboardModuleScssNamespace.IScoreboardModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ScoreboardModuleScssNamespace.IScoreboardModuleScss;
};

export = ScoreboardModuleScssModule;
