// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TopModuleScssNamespace {
  export interface ITopModuleScss {
    gameName: string;
    headerContainer: string;
  }
}

declare const TopModuleScssModule: TopModuleScssNamespace.ITopModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TopModuleScssNamespace.ITopModuleScss;
};

export = TopModuleScssModule;
