// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace GameSectionModuleScssNamespace {
  export interface IGameSectionModuleScss {
    gameArea: string;
    gameOverComponent: string;
    wrapperContainer: string;
  }
}

declare const GameSectionModuleScssModule: GameSectionModuleScssNamespace.IGameSectionModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GameSectionModuleScssNamespace.IGameSectionModuleScss;
};

export = GameSectionModuleScssModule;
